### ISSUE TITLE
Prepare docker environment for LA version 5.27+

### ISSUE THREAD

**Issue by msvihra** [QualityUnit/LiveAgent-Docker#5]
LA version >5.24 introduced ES 7.X requirement and removed support for PHP 7.2 which means containers using PHP and Elasticsearch need to be upgraded to use the latest LA version. As we need to rebuilt `apache-fpm` and `resque` containers we should also install `httpd` in secure way using official CentOS repositories and `resque-server` installation should use [our official public upstream](https://raw.github.com/QualityUnit/resqu-server/5.3.2/build/php-resque-serial-5.3.2.zip).

- [ ] upgrade `elasticsearch` containers and use Elasticsearch 7.16.2.

- [ ] upgrade `resque` containers and use PHP v7.4. `resque` on version 5.3.2 should be installed using this [upstream](https://raw.github.com/QualityUnit/resqu-server/5.3.2/build/php-resque-serial-5.3.2.zip) instead of local zip.

- [ ] upgrade `apache-fpm` containers and use PHP v7.4. 

The issue need to prepare `docker-1_host` and ` docker-4_hosts_2LB` templates.

**Comment by lubo** [comment]
Approved.
