### ISSUE TITLE
Update of Nginx in containers

### ISSUE THREAD

**Issue by msvihra** [QualityUnit/LiveAgent-Docker#7]
The containers, serving LA websites should use latest stable Nginx version available which is [nginx-1.20.2](http://nginx.org/en/download.html) at the time of writing.

**Comment by msvihra** [comment]
Since Nginx on < 1.20.1 versions suffers various bugs and security problems, version used in LiveAgent-Docker need to be upgraded to latest version (1.20.2).

**Proposed solution:**

- Build RPM of Nginx from [latest stable source](http://nginx.org/download/nginx-1.20.2.tar.gz) and add all required modules which are - [lua](https://github.com/openresty/lua-nginx-module), [redis2](https://github.com/openresty/redis2-nginx-module), [push-stream](https://github.com/wandenberg/nginx-push-stream-module) for Nginx used in this environment. RPM will be built on devel VM, using [this state](https://github.com/QualityUnit/QuCloud/blob/713b56572069b554d2941467ad120d7c5042ffbe/QuSalt/salt/roots/devel/nginx/init.sls), since same method was used on currently used version (1.15.8).
- Add new RPM to repo and modify installation paths to match this. This need to be modified in all variations - [docker-1_host](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-1_host) and both LBs used in [docker-4_hosts_2LB](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-4_hosts_2LB).
- Remove unused RPMs after.

**What need to be tested:**

- Nginx containers provisioning.
- Liveagent installation and basic functionality using new Nginx (visitors, events, pagevisits, chats, etc).
- Test containers upgrade.

**Deliverables:**

- One PR adding upgraded Nginx version to all variations, closing issue.

**ETA:**

- 8 hours for PR and test.

**Comment by lubo** [comment]
Approved.
